In [ ]:
import pandas as pd
import numpy as np

In [ ]:

import calendar
import datetime

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_excel (r'/content/drive/MyDrive/office dataset/annotation_file_White Cow_S1006_14_02_22_04PM_15_02_22_01AM.xlsx')
print (df)

      device_id     timestamp            date_time   x       x_g   y  \
0         S1006  1.644846e+09  14/02/2022-19:46:17 -55 -8.430469 -21
1         S1006  1.644846e+09  14/02/2022-19:46:17 -55 -8.430469 -22
2         S1006  1.644846e+09  14/02/2022-19:46:18 -56 -8.583750 -21
3         S1006  1.644846e+09  14/02/2022-19:46:18 -57 -8.737031 -22
4         S1006  1.644846e+09  14/02/2022-19:46:19 -56 -8.583750 -22
...         ...           ...                  ...  ..       ...  ..
43435     S1006  1.644869e+09  15/02/2022-01:59:57 -52 -7.970625 -30
43436     S1006  1.644869e+09  15/02/2022-01:59:58 -53 -8.123906 -29
43437     S1006  1.644869e+09  15/02/2022-01:59:58 -50 -7.664062 -29
43438     S1006  1.644869e+09  15/02/2022-01:59:59 -54 -8.277188 -29
43439     S1006  1.644869e+09  15/02/2022-01:59:59 -49 -7.510781 -31

            y_g   z       z_g  rumination  standing  eating
0     -3.218906  -9 -1.379531         NaN       NaN     NaN
1     -3.372187  -9 -1.379531         NaN       NaN     NaN
2     -3.218906  -9 -1.379531         NaN       NaN     NaN
3     -3.372187  -9 -1.379531         NaN       NaN     NaN
4     -3.372187  -8 -1.226250         NaN       NaN     NaN
...         ...  ..       ...         ...       ...     ...
43435 -4.598438 -10 -1.532812         NaN       NaN     NaN
43436 -4.445156 -10 -1.532812         NaN       NaN     NaN
43437 -4.445156 -13 -1.992656         NaN       NaN     NaN
43438 -4.445156 -16 -2.452500         NaN       NaN     NaN
43439 -4.751719 -15 -2.299219         NaN       NaN     NaN

[43440 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43440 entries, 0 to 43439
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   device_id   43440 non-null  object
 1   timestamp   43440 non-null  float64
 2   date_time   43440 non-null  object
 3   x           43440 non-null  int64
 4   x_g         43440 non-null  float64
 5   y           43440 non-null  int64
 6   y_g         43440 non-null  float64
 7   z           43440 non-null  int64
 8   z_g         43440 non-null  float64
 9   rumination  0 non-null      float64
 10  standing    0 non-null      float64
 11  eating      0 non-null      float64
dtypes: float64(7), int64(3), object(2)
memory usage: 4.0+ MB

In [ ]:
df['timestamp'][0], df['timestamp'][1]

(1644846377.0, 1644846377.5)

In [ ]:
df['timestamp']=df['timestamp'].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43440 entries, 0 to 43439
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   device_id   43440 non-null  object
 1   timestamp   43440 non-null  float64
 2   date_time   43440 non-null  object
 3   x           43440 non-null  int64
 4   x_g         43440 non-null  float64
 5   y           43440 non-null  int64
 6   y_g         43440 non-null  float64
 7   z           43440 non-null  int64
 8   z_g         43440 non-null  float64
 9   rumination  0 non-null      float64
 10  standing    0 non-null      float64
 11  eating      0 non-null      float64
dtypes: float64(7), int64(3), object(2)
memory usage: 4.0+ MB

In [ ]:
df1 = pd.read_excel (r'/content/drive/MyDrive/office dataset/test_validation.xlsx')
df1.head(100)

,Rum_Start_Date,Rum_Start_Time,Rum_Start_Unixtime,Rum_End_Date,Rum_End_Time,Rum_End_Unixtime,Stand_Start_Date,Stand_Start_Time,Stand_Start_Unixtime,Stand_End_Date,Stand_End_Time,Stand_End_Unixtime,Eat_Start_Date,Eat_Start_Time,Eat_Start_Unixtime,Eat_End_Date,Eat_End_Time,Eat_End_Unixtime
0,2022-02-14,17:28:36,NaN,2022-02-14,17:35:16,NaN,2022-02-14,16:08:42,NaN,2022-02-14,16:39:06,NaN,2022-02-14,16:24:23,NaN,2022-02-14,16:39:06,NaN
1,2022-02-14,18:13:07,NaN,2022-02-14,18:30:20,NaN,2022-02-14,17:49:35,NaN,2022-02-14,18:11:26,NaN,2022-02-14,17:57:00,NaN,2022-02-14,18:06:50,NaN
2,2022-02-14,19:09:43,NaN,2022-02-14,19:30:25,NaN,2022-02-14,18:29:24,NaN,2022-02-14,18:59:59,NaN,2022-02-14,18:32:21,NaN,2022-02-14,18:59:59,NaN
3,2022-02-14,20:26:42,NaN,2022-02-14,20:39:34,NaN,2022-02-14,19:00:00,NaN,2022-02-14,19:30:25,NaN,2022-02-14,19:00:00,NaN,2022-02-14,19:00:27,NaN
4,2022-02-14,21:15:31,NaN,2022-02-14,21:52:20,NaN,2022-02-14,20:19:02,NaN,2022-02-14,20:59:59,NaN,2022-02-14,20:39:28,NaN,2022-02-14,20:59:59,NaN
5,2022-02-14,22:46:54,NaN,2022-02-14,22:59:59,NaN,2022-02-14,21:00:01,NaN,2022-02-14,21:07:20,NaN,2022-02-14,21:00:01,NaN,2022-02-14,21:06:05,NaN
6,2022-02-14,23:00:00,NaN,2022-02-14,23:34:40,NaN,2022-02-14,23:00:00,NaN,2022-02-14,23:08:49,NaN,2022-02-15,01:09:15,NaN,2022-02-15,01:24:15,NaN
7,2022-02-15,00:23:43,NaN,2022-02-15,00:59:59,NaN,2022-02-15,01:07:09,NaN,2022-02-15,01:28:42,NaN,NaT,NaN,NaN,NaT,NaN,NaN
8,2022-02-15,01:00:10,NaN,2022-02-15,01:04:34,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN
9,2022-02-15,01:35:41,NaN,2022-02-15,01:59:59,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN

In [ ]:
df1['Rum_Start_Unixtime'] = df1['Rum_Start_Date'].astype(str) + ' '+ df1['Rum_Start_Time'].astype(str)

In [ ]:
df1['Rum_Start_Unixtime']=df1['Rum_Start_Unixtime'].astype(str)

In [ ]:
df1['Rum_End_Unixtime'] = df1['Rum_End_Date'].astype(str) + ' '+ df1['Rum_End_Time'].astype(str)

In [ ]:
df1.head(10)

,Rum_Start_Date,Rum_Start_Time,Rum_Start_Unixtime,Rum_End_Date,Rum_End_Time,Rum_End_Unixtime,Stand_Start_Date,Stand_Start_Time,Stand_Start_Unixtime,Stand_End_Date,Stand_End_Time,Stand_End_Unixtime,Eat_Start_Date,Eat_Start_Time,Eat_Start_Unixtime,Eat_End_Date,Eat_End_Time,Eat_End_Unixtime
0,2022-02-14,17:28:36,2022-02-14 17:28:36,2022-02-14,17:35:16,2022-02-14 17:35:16,2022-02-14,16:08:42,NaN,2022-02-14,16:39:06,NaN,2022-02-14,16:24:23,NaN,2022-02-14,16:39:06,NaN
1,2022-02-14,18:13:07,2022-02-14 18:13:07,2022-02-14,18:30:20,2022-02-14 18:30:20,2022-02-14,17:49:35,NaN,2022-02-14,18:11:26,NaN,2022-02-14,17:57:00,NaN,2022-02-14,18:06:50,NaN
2,2022-02-14,19:09:43,2022-02-14 19:09:43,2022-02-14,19:30:25,2022-02-14 19:30:25,2022-02-14,18:29:24,NaN,2022-02-14,18:59:59,NaN,2022-02-14,18:32:21,NaN,2022-02-14,18:59:59,NaN
3,2022-02-14,20:26:42,2022-02-14 20:26:42,2022-02-14,20:39:34,2022-02-14 20:39:34,2022-02-14,19:00:00,NaN,2022-02-14,19:30:25,NaN,2022-02-14,19:00:00,NaN,2022-02-14,19:00:27,NaN
4,2022-02-14,21:15:31,2022-02-14 21:15:31,2022-02-14,21:52:20,2022-02-14 21:52:20,2022-02-14,20:19:02,NaN,2022-02-14,20:59:59,NaN,2022-02-14,20:39:28,NaN,2022-02-14,20:59:59,NaN
5,2022-02-14,22:46:54,2022-02-14 22:46:54,2022-02-14,22:59:59,2022-02-14 22:59:59,2022-02-14,21:00:01,NaN,2022-02-14,21:07:20,NaN,2022-02-14,21:00:01,NaN,2022-02-14,21:06:05,NaN
6,2022-02-14,23:00:00,2022-02-14 23:00:00,2022-02-14,23:34:40,2022-02-14 23:34:40,2022-02-14,23:00:00,NaN,2022-02-14,23:08:49,NaN,2022-02-15,01:09:15,NaN,2022-02-15,01:24:15,NaN
7,2022-02-15,00:23:43,2022-02-15 00:23:43,2022-02-15,00:59:59,2022-02-15 00:59:59,2022-02-15,01:07:09,NaN,2022-02-15,01:28:42,NaN,NaT,NaN,NaN,NaT,NaN,NaN
8,2022-02-15,01:00:10,2022-02-15 01:00:10,2022-02-15,01:04:34,2022-02-15 01:04:34,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN
9,2022-02-15,01:35:41,2022-02-15 01:35:41,2022-02-15,01:59:59,2022-02-15 01:59:59,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN

this is for stand_unix time

In [ ]:
import dateutil.parser
my_date = df1['Rum_Start_Unixtime'].astype(str)
my_date2=df1['Rum_End_Unixtime'].astype(str)
date_time = list(map(dateutil.parser.parse, my_date))
date_time2= list(map(dateutil.parser.parse, my_date2))
df2 = df1.copy(deep=True)
tzinfos = {"BST": dateutil.tz.gettz("Asia/Dhaka")}
df2['Rum_Start_Unixtime'] = df1['Rum_Start_Unixtime'].apply(lambda x :  dateutil.parser.parse(x, tzinfos=tzinfos).timestamp()-6*60*60)
df2['Rum_End_Unixtime'] = df1['Rum_End_Unixtime'].apply(lambda x :  dateutil.parser.parse(x, tzinfos=tzinfos).timestamp()-6*60*60)
print(df2.head())
# print(my_ts)

  Rum_Start_Date Rum_Start_Time  Rum_Start_Unixtime Rum_End_Date Rum_End_Time  \
0     2022-02-14       17:28:36        1.644838e+09   2022-02-14     17:35:16
1     2022-02-14       18:13:07        1.644841e+09   2022-02-14     18:30:20
2     2022-02-14       19:09:43        1.644844e+09   2022-02-14     19:30:25
3     2022-02-14       20:26:42        1.644849e+09   2022-02-14     20:39:34
4     2022-02-14       21:15:31        1.644852e+09   2022-02-14     21:52:20

   Rum_End_Unixtime Stand_Start_Date Stand_Start_Time  Stand_Start_Unixtime  \
0      1.644839e+09       2022-02-14         16:08:42                   NaN
1      1.644842e+09       2022-02-14         17:49:35                   NaN
2      1.644845e+09       2022-02-14         18:29:24                   NaN
3      1.644850e+09       2022-02-14         19:00:00                   NaN
4      1.644854e+09       2022-02-14         20:19:02                   NaN

  Stand_End_Date Stand_End_Time  Stand_End_Unixtime Eat_Start_Date  \
0     2022-02-14       16:39:06                 NaN     2022-02-14
1     2022-02-14       18:11:26                 NaN     2022-02-14
2     2022-02-14       18:59:59                 NaN     2022-02-14
3     2022-02-14       19:30:25                 NaN     2022-02-14
4     2022-02-14       20:59:59                 NaN     2022-02-14

  Eat_Start_Time  Eat_Start_Unixtime Eat_End_Date Eat_End_Time  \
0       16:24:23                 NaN   2022-02-14     16:39:06
1       17:57:00                 NaN   2022-02-14     18:06:50
2       18:32:21                 NaN   2022-02-14     18:59:59
3       19:00:00                 NaN   2022-02-14     19:00:27
4       20:39:28                 NaN   2022-02-14     20:59:59

   Eat_End_Unixtime
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN

In [ ]:
df2['Rum_Start_Unixtime']=df2['Rum_Start_Unixtime'].astype(float)
df2['Rum_End_Unixtime']=df2['Rum_End_Unixtime'].astype(float)

In [ ]:
df2.head(10)

,Rum_Start_Date,Rum_Start_Time,Rum_Start_Unixtime,Rum_End_Date,Rum_End_Time,Rum_End_Unixtime,Stand_Start_Date,Stand_Start_Time,Stand_Start_Unixtime,Stand_End_Date,Stand_End_Time,Stand_End_Unixtime,Eat_Start_Date,Eat_Start_Time,Eat_Start_Unixtime,Eat_End_Date,Eat_End_Time,Eat_End_Unixtime
0,2022-02-14,17:28:36,1.644838e+09,2022-02-14,17:35:16,1.644839e+09,2022-02-14,16:08:42,NaN,2022-02-14,16:39:06,NaN,2022-02-14,16:24:23,NaN,2022-02-14,16:39:06,NaN
1,2022-02-14,18:13:07,1.644841e+09,2022-02-14,18:30:20,1.644842e+09,2022-02-14,17:49:35,NaN,2022-02-14,18:11:26,NaN,2022-02-14,17:57:00,NaN,2022-02-14,18:06:50,NaN
2,2022-02-14,19:09:43,1.644844e+09,2022-02-14,19:30:25,1.644845e+09,2022-02-14,18:29:24,NaN,2022-02-14,18:59:59,NaN,2022-02-14,18:32:21,NaN,2022-02-14,18:59:59,NaN
3,2022-02-14,20:26:42,1.644849e+09,2022-02-14,20:39:34,1.644850e+09,2022-02-14,19:00:00,NaN,2022-02-14,19:30:25,NaN,2022-02-14,19:00:00,NaN,2022-02-14,19:00:27,NaN
4,2022-02-14,21:15:31,1.644852e+09,2022-02-14,21:52:20,1.644854e+09,2022-02-14,20:19:02,NaN,2022-02-14,20:59:59,NaN,2022-02-14,20:39:28,NaN,2022-02-14,20:59:59,NaN
5,2022-02-14,22:46:54,1.644857e+09,2022-02-14,22:59:59,1.644858e+09,2022-02-14,21:00:01,NaN,2022-02-14,21:07:20,NaN,2022-02-14,21:00:01,NaN,2022-02-14,21:06:05,NaN
6,2022-02-14,23:00:00,1.644858e+09,2022-02-14,23:34:40,1.644860e+09,2022-02-14,23:00:00,NaN,2022-02-14,23:08:49,NaN,2022-02-15,01:09:15,NaN,2022-02-15,01:24:15,NaN
7,2022-02-15,00:23:43,1.644863e+09,2022-02-15,00:59:59,1.644865e+09,2022-02-15,01:07:09,NaN,2022-02-15,01:28:42,NaN,NaT,NaN,NaN,NaT,NaN,NaN
8,2022-02-15,01:00:10,1.644865e+09,2022-02-15,01:04:34,1.644865e+09,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN
9,2022-02-15,01:35:41,1.644867e+09,2022-02-15,01:59:59,1.644869e+09,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN

In [ ]:
print(df2.Rum_Start_Unixtime[0])
print(df2.Rum_Start_Unixtime[1])

1644838116.0
1644840787.0

In [ ]:
df['timestamp'].count()

43440

This is for the Rumination ✌

In [ ]:
for j in range (len(df2)):
    start =df2["Rum_Start_Unixtime"].values[j]
    end= df2["Rum_End_Unixtime"].values[j]
    print(start,end)

1644838116.0 1644838516.0
1644840787.0 1644841820.0
1644844183.0 1644845425.0
1644848802.0 1644849574.0
1644851731.0 1644853940.0
1644857214.0 1644857999.0
1644858000.0 1644860080.0
1644863023.0 1644865199.0
1644865210.0 1644865474.0
1644867341.0 1644868799.0

In [ ]:
for j in range (len(df2.Rum_Start_Unixtime)):
    start =df2["Rum_Start_Unixtime"].values[j]
    end= df2["Rum_End_Unixtime"].values[j]
    for i in range (len(df)):
        if (df['timestamp'].values[i]>=start) and (df['timestamp'].values[i]<=end):
          df['rumination'].values[i]=1

In [ ]:
df['timestamp'][0],df['timestamp'][1]

(1644846377.0, 1644846377.5)

In [ ]:
df['rumination'].value_counts()

1.0    18917
Name: rumination, dtype: int64

In [ ]:
df['rumination'] = df['rumination'].fillna(0)

This is for the standing 🐈

In [ ]:
df1['Stand_Start_Unixtime'] = df1['Stand_Start_Date'].astype(str) + ' '+ df1['Stand_Start_Time'].astype(str)

In [ ]:
df1['Stand_Start_Unixtime']=df1['Stand_Start_Unixtime'].astype(str)

In [ ]:
df1['Stand_End_Unixtime'] = df1['Stand_End_Date'].astype(str) + ' '+ df1['Stand_End_Time'].astype(str)

In [ ]:
import dateutil.parser
my_date = df1['Stand_Start_Unixtime'].astype(str)
my_date2=df1['Stand_End_Unixtime'].astype(str)
date_time = list(map(dateutil.parser.parse, my_date))
date_time2= list(map(dateutil.parser.parse, my_date2))
df2 = df1.copy(deep=True)
tzinfos = {"BST": dateutil.tz.gettz("Asia/Dhaka")}
df2['Stand_Start_Unixtime'] = df1['Stand_Start_Unixtime'].apply(lambda x :  dateutil.parser.parse(x, tzinfos=tzinfos).timestamp()-6*60*60)
df2['Stand_End_Unixtime'] = df1['Stand_End_Unixtime'].apply(lambda x :  dateutil.parser.parse(x, tzinfos=tzinfos).timestamp()-6*60*60)
print(df2.head())

ParserError: ignored

In [ ]:
f = open('/content/drive/MyDrive/office dataset/newcowanotation.csv', 'w')

In [ ]:
df.to_csv("/content/drive/MyDrive/office dataset/newcowanotation.csv", index=False)